from app.api.auth import router as auth_router
from app.api.admin import router as admin_router
from app.api.imports import router as imports_router
from app.api.products import router as products_router
from app.api.orders import router as orders_router
from app.api.reports import router as reports_router
from app.api.accounts_receivable import router as accounts_receivable_router
from app.api.suppliers import router as suppliers_router
from app.api.logistics import router as logistics_router
from app.api.purchase_orders import router as purchase_orders_router
from app.api.calendar import router as calendar_router
from app.api.kpi import router as kpi_router
from app.api.new_product import router as new_product_router
from app.api.sales_report import router as sales_report_router
from app.api.inventory_count import router as inventory_count_router
from app.api.erkhet_auto import router as erkhet_auto_router
from app.api.receivings import router as receivings_router
from app.api.bank_statements import router as bank_statements_router
from app.api.expiration import router as expiration_router
from app.api.documents import router as documents_router
from app.api.product_monthly_sales import router as product_monthly_sales_router
from app.api.product_yearly_movement import router as product_yearly_movement_router
from app.api.income_file import router as income_file_router
from app.api.balance_file import router as balance_file_router
from app.api.tag_location_check import router as tag_location_check_router
from app.api.attendance import router as attendance_router
from app.api.ebarimt_report import router as ebarimt_router
from app.api.ai_chat import router as ai_chat_router
from app.api.pos_sync import router as pos_sync_router
from app.api.digest import router as digest_router
from app.api.pos_recon import router as pos_recon_router
from app.api.price_check import router as price_check_router
from app.api.hall_count import router as hall_count_router
from app.api.pallets import router as pallets_router
from app.api.custom_master import router as custom_master_router
